### ISSUE TITLE
mock community data generation notebook?

### ISSUE THREAD

**Issue by nbokulich** [nbokulich/short-read-tax-assignment#1]
@gregcaporaso @benkaehler should we add a notebook demonstrating how to generate (from raw mock community fastqs) empty biom tables and seq rep sets ready for taxonomy assignment?

My initial feeling is that this may be unnecessary, given that it is such a basic process and we just supply these materials for multiple datasets ready for analysis.

*However,* we might want to update these materials anyway, using ``QIIME2`` instead of ``QIIME1`` (though this carries the risk that we may need to change some functions in the existing notebooks).

Thoughts?

**Comment by gregcaporaso** [comment]
I think it would be a good idea to update these to use QIIME 2 - one benefit of doing that is that we wouldn't really need to provide notebooks (though a markdown file would be nice), we could just provide links that would allow viewing of artifact provenance. What would you guys need to make this happen?

**Comment by nbokulich** [comment]
sounds good — though until we have a ``provenance2pipeline`` converter, a notebook or markdown file would make it easier to replicate this pipeline on other mock communities.

I will just start out by making a notebook to organize my own thoughts — and then we can delete or convert to markdown later if we deem it unnecessary.

I should be able to figure out a pipeline for this with Artifact API, though if you or someone else already has a notebook or list of artifact API commands for processing fastq-->feature-table (I've been doing this all CLI), that will speed things up.

**Comment by gregcaporaso** [comment]
Great - doing this with notebooks and the artifact API would actually be pretty valuable (for testing, and potentially to port to QIIME 2 documentation) so I think it's a good idea. I don't have those notebooks, though @johnchase might have some that he can share with you. If not, you're just translating CLI to artifact API calls, so once you figure it out for one command it'll translate easily to the others.

**Comment by nbokulich** [comment]
What file formats should we deposit in the repo? We currently have qiime1 biom tables for each mock community. Should we convert qiime2 artifacts that I generate into biom tables? That way we support more general use, don't require having qiime2 installed to use.

**Comment by gregcaporaso** [comment]
What if we did both the biom file exported from the qza, and the qza
itself? That way people who do want to use with QIIME 2 don't lose the
provenance of the artifacts, but it's still easy for non-QIIME 2 users.

On Wed, Nov 30, 2016 at 2:23 PM, Nicholas Bokulich <notifications@github.com

**Comment by nbokulich** [comment]
Sounds like a plan. I can do the same with the sample metadata and tree files. Thanks!

**Comment by gregcaporaso** [comment]
Thanks! Note that the sample metadata should be the same file for both
QIIME 1 and QIIME 2.

**Comment by nbokulich** [comment]
@gregcaporaso notebook is done! Notebook [here](https://github.com/nbokulich/short-read-tax-assignment/blob/master/ipynb/mock-community/mock-dataset-generation.ipynb) and relevant code [here](https://github.com/nbokulich/short-read-tax-assignment/blob/master/tax_credit/process_mocks.py).

This should be very easily adaptable to use on any files, though it is currently set up for batch file processing.

All mock communities are now processed, and new data is located [here](https://github.com/nbokulich/short-read-tax-assignment/tree/master/data/mock-community). (Note that old mock community dirs are still there, I will delete once I get taxonomy assignments for the new data)

Let me know what you think! I hope it's not too ugly...

**Comment by gregcaporaso** [comment]
Looks good from a quick glance @nbokulich, would you like me to do a detailed review of this now?

**Comment by nbokulich** [comment]
If you have the time, but if not this is not holding me up.

**Comment by gregcaporaso** [comment]
Ok, I'll plan to do it as we progress a little more with the analysis of the new classifiers then as I'm going to be pretty tied up with travel this week.

**Comment by nbokulich** [comment]
[done](https://github.com/nbokulich/short-read-tax-assignment/blob/master/ipynb/mock-community/mock-dataset-generation.ipynb)
